# python calculate_pert_metrics.py --basepath output/Healthy/healthy_chain_1/perturbations/ --pert-start 20 --pert-end 40 --dt 0.1 --subjset output/Healthy/input/subjset.pkl --leave-out-table output/Healthy/healthy_chain_1.csv --outfile output/Healthy/healthy_chain_1_perturbation.tsv
# python calculate_pert_metrics.py --basepath output/Healthy/healthy_chain_2/perturbations/ --pert-start 20 --pert-end 40 --dt 0.1 --subjset output/Healthy/input/subjset.pkl --leave-out-table output/Healthy/healthy_chain_2.csv --outfile output/Healthy/healthy_chain_2_perturbation.tsv
# python calculate_pert_metrics.py --basepath output/Healthy/healthy_chain_3/perturbations/ --pert-start 20 --pert-end 40 --dt 0.1 --subjset output/Healthy/input/subjset.pkl --leave-out-table output/Healthy/healthy_chain_3.csv --outfile output/Healthy/healthy_chain_3_perturbation.tsv
# python calculate_pert_metrics.py --basepath output/Healthy/healthy_cycle_2/perturbations/ --pert-start 20 --pert-end 40 --dt 0.1 --subjset output/Healthy/input/subjset.pkl --leave-out-table output/Healthy/healthy_cycle_2.csv --outfile output/Healthy/healthy_cycle_2_perturbation.tsv
# python calculate_pert_metrics.py --basepath output/Healthy/healthy_cycle_3/perturbations/ --pert-start 20 --pert-end 40 --dt 0.1 --subjset output/Healthy/input/subjset.pkl --leave-out-table output/Healthy/healthy_cycle_3.csv --outfile output/Healthy/healthy_cycle_3_perturbation.tsv
# python calculate_pert_metrics.py --basepath output/Healthy/healthy_asvs/perturbations/ --pert-start 20 --pert-end 40 --dt 0.1 --subjset output/Healthy/input/subjset.pkl --leave-out-table output/Healthy/healthy_asvs.txt --outfile output/Healthy/healthy_asvs_perturbation.tsv
# python calculate_pert_metrics.py --basepath output/Healthy/healthy_cluster/perturbations/ --pert-start 20 --pert-end 40 --dt 0.1 --subjset output/Healthy/input/subjset.pkl --leave-out-table output/Healthy/healthy_cluster.csv --outfile output/Healthy/healthy_cluster_perturbation.tsv

# python calculate_pert_metrics.py --basepath output/UC/uc_chain_1/perturbations/ --pert-start 20 --pert-end 40 --dt 0.1 --subjset output/UC/input/subjset.pkl --leave-out-table output/UC/uc_chain_1.csv --outfile output/UC/uc_chain_1_perturbation.tsv
# python calculate_pert_metrics.py --basepath output/UC/uc_chain_2/perturbations/ --pert-start 20 --pert-end 40 --dt 0.1 --subjset output/UC/input/subjset.pkl --leave-out-table output/UC/uc_chain_2.csv --outfile output/UC/uc_chain_2_perturbation.tsv
# python calculate_pert_metrics.py --basepath output/UC/uc_chain_3/perturbations/ --pert-start 20 --pert-end 40 --dt 0.1 --subjset output/UC/input/subjset.pkl --leave-out-table output/UC/uc_chain_3.csv --outfile output/UC/uc_chain_3_perturbation.tsv
# python calculate_pert_metrics.py --basepath output/UC/uc_cycle_2/perturbations/ --pert-start 20 --pert-end 40 --dt 0.1 --subjset output/UC/input/subjset.pkl --leave-out-table output/UC/uc_cycle_2.csv --outfile output/UC/uc_cycle_2_perturbation.tsv
# python calculate_pert_metrics.py --basepath output/UC/uc_cycle_3/perturbations/ --pert-start 20 --pert-end 40 --dt 0.1 --subjset output/UC/input/subjset.pkl --leave-out-table output/UC/uc_cycle_3.csv --outfile output/UC/uc_cycle_3_perturbation.tsv
python calculate_pert_metrics.py --basepath output/UC/uc_asvs/perturbations/ --pert-start 20 --pert-end 40 --dt 0.1 --subjset output/UC/input/subjset.pkl --leave-out-table output/UC/uc_asvs.txt --outfile output/UC/uc_asvs_perturbation.tsv
python calculate_pert_metrics.py --basepath output/UC/uc_cluster/perturbations/ --pert-start 20 --pert-end 40 --dt 0.1 --subjset output/UC/input/subjset.pkl --leave-out-table output/UC/uc_cluster.csv --outfile output/UC/uc_cluster_perturbation.tsv



